/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GoodbyeWorld {
    }
}
declare global {
    interface HTMLGoodbyeWorldElement extends Components.GoodbyeWorld, HTMLStencilElement {
    }
    var HTMLGoodbyeWorldElement: {
        prototype: HTMLGoodbyeWorldElement;
        new (): HTMLGoodbyeWorldElement;
    };
    interface HTMLElementTagNameMap {
        "goodbye-world": HTMLGoodbyeWorldElement;
    }
}
declare namespace LocalJSX {
    interface GoodbyeWorld {
    }
    interface IntrinsicElements {
        "goodbye-world": GoodbyeWorld;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "goodbye-world": LocalJSX.GoodbyeWorld & JSXBase.HTMLAttributes<HTMLGoodbyeWorldElement>;
        }
    }
}
